### ISSUE TITLE
Make scanBrowser default

### ISSUE THREAD

**Issue by denis-sokolov** [twada/licensify#5]
_(Thank you for your work, this is a great plugin. The following is not criticism, but rather an inquiry, a suggestion.)_

I may be missing a use case here, but if the user is using licensify, he probably wants to cover all dependencies. If he has any `browser` dependencies, what's the use case to _not_ include them in?
If there isn't a clear one, it's always better to just do the correct thing from the start, without requiring extra options. Taking this further, why is this option beneficial?

**Comment by armorik83** [comment]
:+1:

**Comment by twada** [comment]
Hi @denis-sokolov, thank you for your suggestion!

> it's always better to just do the correct thing from the start, without requiring extra options.

Your suggestion seems to be a reasonable default for licensify.
It's also a breaking change, so I'll cut a major bump release (2.0.0) soon.

Thank you!

**Comment by denis-sokolov** [comment]
I was actually thinking about it, whether it is a breaking change, though.
I doubt it breaks any use cases, and I estimate it to _fix_ some use cases for people who did not know they are not adding all licenses.
I see a reason to think this might be a compatible change to the existing version.

It's just an idea, of course. You know the context and yours is the final call to make.

**Comment by twada** [comment]
Thank you for your thoughtful comment.
Let me explain my opinion.

Now, let's discuss in [Symfony's pull-req format](http://symfony.com/doc/current/contributing/code/patches.html#make-a-pull-request). It clears things up a lot.

| Q             | A
| ------------- | ---
| Bug fix?      | [yes\|no]
| New feature?  | [yes\|no]
| BC breaks?    | [yes\|no]
| Deprecations? | [yes\|no]
| Tests pass?   | yes
| Fixed tickets | #5


> I estimate it to fix some use cases for people who did not know they are not adding all licenses.

I rephrase your comment to a few questions and my answers.

Q. Is ignoring `browser` field by default (not adding all licenses) a bug or a feature?
A. It's a feature. Because it is documented in README.

It's also a bad design decision made by me. I should have made it a default. Ignoring `browser` field by default is nearly a bug, but intentional feature.

Q. Is scanning `browser` field by default a new feature?
A. If it is not a bug, it might be a new feature.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | [yes\|no]
| Deprecations? | [yes\|no]
| Tests pass?   | yes
| Fixed tickets | #5

Q. Does scanning `browser` field by default break any use cases?
A. Maybe, No.

Q. Is scanning `browser` field by default considered to be a breaking change?
A. Yes.

I think, in general, changing default behavior is a breaking change.
Bumping major version prevents licensify from affecting any build artifacts that users are not aware of.

Bumping major version is decided whether it is a breaking change or not.
So, if it is a breaking change, it must be a major bump.
Licensify is still a young product and I'm not afraid of bumping major version at this time.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | [yes\|no]
| Tests pass?   | yes
| Fixed tickets | #5

Q. Is there any user who do not want to add `browser` field dependencies?
A. Hmm, if not, I should deprecate `scanBrowser` option and make licensify always scan `browser` field. If there are some users, changing default value of `scanBrowser` to `true` might be appropriate.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Deprecations? | maybe?
| Tests pass?   | yes
| Fixed tickets | #5

Any thoughts?

**Comment by denis-sokolov** [comment]
I've suggested a second opinion whether or not it is a BC change. You seem to have reached a reasonable conclusion. I don't think there's much to discuss remaining. You need to go along with your decision. I'm happy with the package, regardless of whether or not you'll put that in 2.0.0 or 1.6.0, good work! :)

**Comment by twada** [comment]
Thanks again @denis-sokolov! Your suggestion makes me think deeper. It's time to go ahead ;)

**Comment by twada** [comment]
[2.0.0](https://github.com/twada/licensify/releases/tag/v2.0.0) is out. Thank you for your suggestion!
